previewsEnabled: true
databases:
  - name: railscanaryeu
    region: frankfurt
    databaseName: railscanaryeu
    user: railscanary

services:
  - type: web
    name: railscanaryeu
    region: frankfurt
    plan: Standard Plus
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: railscanaryeu
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: redis
          type: pserv
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          type: pserv
          property: port
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PERMITTED_USERS
        value: someone@email.com
      - key: PERMITTED_SENDERS
        value: someone@email.com
  - type: pserv
    name: redis
    region: frankfurt
    env: docker
    repo: https://github.com/render-examples/redis.git
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 10
