previewsEnabled: true
databases:
  - name: railscanaryeu
    region: frankfurt
    databaseName: railscanaryeu
    user: railscanary

services:
  - type: web
    name: railscanaryeu
    region: frankfurt
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/startRender.sh"
    envVars:
      - fromGroup: jb-test-group
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: railscanaryeu
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: rediseu
          type: pserv
          property: host
      - key: REDIS_PORT
        fromService:
          name: rediseu
          type: pserv
          property: port
      - key: REDIS_HOSTPORT
        fromService:
          name: rediseu
          type: pserv
          property: hostport
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PERMITTED_USERS
        value: someone@email.com
      - key: PERMITTED_SENDERS
        value: someone@email.com
  - type: pserv
    name: rediseu
    region: frankfurt
    env: docker
    repo: https://github.com/render-examples/redis.git
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 10
